### ISSUE TITLE
"What is the meaning of life" original test issue

### ISSUE THREAD

**Issue by Jazzwall** [swarmfund/swarm-static-website#4]
This is a test.  setting up an original issue here and will next test to see if I can crosslink this to an issue in "allyourcoinsarebelongtous"

**Comment by Jazzwall** [comment]
Test comment.  Meaning of life is still unknown.

**Comment by Jazzwall** [comment]
Turns out, we don't need to cross link issues for Waffle board.  The board can reflect multiple repos in an org.

**Comment by wires** [comment]
There is also github projects, does most of the waffle, check it out...

**Comment by Jazzwall** [comment]
Yep.  Waffle does what Github Projects do, however, the workflow in using github projects is more involved.. https://what.thedailywtf.com/topic/22435/github-projects-vs-waffle
